<div class="AllBg _BK000000 hide"></div>
<div class="MsgBox hide">
	<div class="Msg">
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
		XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	</div>
	<input class="MsgOk BtnStyle2 FontSize16 _BK2e73dc _FCffffff hide" type="button" value="OK">
	<input class="MsgYes BtnStyle2 FontSize16 _BK2e73dc _FCffffff hide" type="button" value="Yes">
	<input class="MsgNo BtnStyle2 FontSize16 _BK49a211 _FCffffff hide" type="button" value="No">
</div>